version: '3.8'

services:
  world-engine:
    build:
      context: .
      dockerfile: WorldEngine/Dockerfile
    ports:
      - "50051:50051"
    networks:
      - swarm-net
    container_name: world-engine

  robot:
    build:
      context: .
      dockerfile: Robot/Dockerfile
    # Robot will derive a unique ID from the container hostname when not provided.
    command: [ "--world-engine=world-engine:50051" ]
    depends_on:
      - world-engine
    networks:
      - swarm-net
    ports:
      - "8081"
    deploy:
     replicas: 5

  visualiser:
    build:
      context: .
      dockerfile: Visualiser/Dockerfile
    ports:
      - "3000:8080"
    depends_on:
      - world-engine
    networks:
      - swarm-net

networks:
  swarm-net:
    driver: bridge
