// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: proto/robot.proto

package communications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	RobotId string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	// Absolute target position in world coordinates
	TargetX float64 `protobuf:"fixed64,2,opt,name=target_x,json=targetX,proto3" json:"target_x,omitempty"`
	TargetY float64 `protobuf:"fixed64,3,opt,name=target_y,json=targetY,proto3" json:"target_y,omitempty"`
	// Desired heading (radians) when the robot arrives at the target
	DesiredHeading float64 `protobuf:"fixed64,4,opt,name=desired_heading,json=desiredHeading,proto3" json:"desired_heading,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_proto_robot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{0}
}

func (x *MoveRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *MoveRequest) GetTargetX() float64 {
	if x != nil {
		return x.TargetX
	}
	return 0
}

func (x *MoveRequest) GetTargetY() float64 {
	if x != nil {
		return x.TargetY
	}
	return 0
}

func (x *MoveRequest) GetDesiredHeading() float64 {
	if x != nil {
		return x.DesiredHeading
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_proto_robot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{1}
}

func (x *MoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorRequest) Reset() {
	*x = SensorRequest{}
	mi := &file_proto_robot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorRequest) ProtoMessage() {}

func (x *SensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorRequest.ProtoReflect.Descriptor instead.
func (*SensorRequest) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{2}
}

func (x *SensorRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type ObjectData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectData) Reset() {
	*x = ObjectData{}
	mi := &file_proto_robot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectData) ProtoMessage() {}

func (x *ObjectData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectData.ProtoReflect.Descriptor instead.
func (*ObjectData) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectData) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ObjectData) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ObjectData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*ObjectData          `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorResponse) Reset() {
	*x = SensorResponse{}
	mi := &file_proto_robot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorResponse) ProtoMessage() {}

func (x *SensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorResponse.ProtoReflect.Descriptor instead.
func (*SensorResponse) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{4}
}

func (x *SensorResponse) GetObjects() []*ObjectData {
	if x != nil {
		return x.Objects
	}
	return nil
}

type NetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkRequest) Reset() {
	*x = NetworkRequest{}
	mi := &file_proto_robot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkRequest) ProtoMessage() {}

func (x *NetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkRequest.ProtoReflect.Descriptor instead.
func (*NetworkRequest) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type NetworkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetRobotId string                 `protobuf:"bytes,1,opt,name=target_robot_id,json=targetRobotId,proto3" json:"target_robot_id,omitempty"`
	Bandwidth     float64                `protobuf:"fixed64,2,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Latency       float64                `protobuf:"fixed64,3,opt,name=latency,proto3" json:"latency,omitempty"`
	Reliability   float64                `protobuf:"fixed64,4,opt,name=reliability,proto3" json:"reliability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkData) Reset() {
	*x = NetworkData{}
	mi := &file_proto_robot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkData) ProtoMessage() {}

func (x *NetworkData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkData.ProtoReflect.Descriptor instead.
func (*NetworkData) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkData) GetTargetRobotId() string {
	if x != nil {
		return x.TargetRobotId
	}
	return ""
}

func (x *NetworkData) GetBandwidth() float64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *NetworkData) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *NetworkData) GetReliability() float64 {
	if x != nil {
		return x.Reliability
	}
	return 0
}

type NetworkResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NetworkConditions []*NetworkData         `protobuf:"bytes,1,rep,name=network_conditions,json=networkConditions,proto3" json:"network_conditions,omitempty"`
	SimulationPaused  bool                   `protobuf:"varint,2,opt,name=simulation_paused,json=simulationPaused,proto3" json:"simulation_paused,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkResponse) Reset() {
	*x = NetworkResponse{}
	mi := &file_proto_robot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkResponse) ProtoMessage() {}

func (x *NetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkResponse.ProtoReflect.Descriptor instead.
func (*NetworkResponse) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkResponse) GetNetworkConditions() []*NetworkData {
	if x != nil {
		return x.NetworkConditions
	}
	return nil
}

func (x *NetworkResponse) GetSimulationPaused() bool {
	if x != nil {
		return x.SimulationPaused
	}
	return false
}

type HeartbeatRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	RobotId string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	X       float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y       float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Heading float64                `protobuf:"fixed64,4,opt,name=heading,proto3" json:"heading,omitempty"`
	// Leader ID this robot currently believes is authoritative.
	// Empty when no leader is currently known.
	KnownLeaderId string `protobuf:"bytes,5,opt,name=known_leader_id,json=knownLeaderId,proto3" json:"known_leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_robot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *HeartbeatRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *HeartbeatRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *HeartbeatRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *HeartbeatRequest) GetKnownLeaderId() string {
	if x != nil {
		return x.KnownLeaderId
	}
	return ""
}

type HeartbeatResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Canonical position and heading as maintained by the WorldEngine
	X             float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Heading       float64 `protobuf:"fixed64,4,opt,name=heading,proto3" json:"heading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_robot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *HeartbeatResponse) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *HeartbeatResponse) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

type PeerSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // For simulating large payloads (e.g. map sync)
	LamportClock  int64                  `protobuf:"varint,3,opt,name=lamport_clock,json=lamportClock,proto3" json:"lamport_clock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerSyncRequest) Reset() {
	*x = PeerSyncRequest{}
	mi := &file_proto_robot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSyncRequest) ProtoMessage() {}

func (x *PeerSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSyncRequest.ProtoReflect.Descriptor instead.
func (*PeerSyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{10}
}

func (x *PeerSyncRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *PeerSyncRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PeerSyncRequest) GetLamportClock() int64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

type PeerSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerSyncResponse) Reset() {
	*x = PeerSyncResponse{}
	mi := &file_proto_robot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSyncResponse) ProtoMessage() {}

func (x *PeerSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSyncResponse.ProtoReflect.Descriptor instead.
func (*PeerSyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{11}
}

func (x *PeerSyncResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

type RoutedMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`                // Original sender
	DestinationId string                 `protobuf:"bytes,2,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"` // Final target
	MessageType   string                 `protobuf:"bytes,3,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`       // "RequestVote", "VoteResponse", "AppendEntries", "AppendEntriesResponse"
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                  // Serialized inner RPC message
	Ttl           int32                  `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`                                         // Decremented each hop; dropped at 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutedMessageRequest) Reset() {
	*x = RoutedMessageRequest{}
	mi := &file_proto_robot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutedMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutedMessageRequest) ProtoMessage() {}

func (x *RoutedMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutedMessageRequest.ProtoReflect.Descriptor instead.
func (*RoutedMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{12}
}

func (x *RoutedMessageRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *RoutedMessageRequest) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *RoutedMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *RoutedMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RoutedMessageRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type RoutedMessageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Delivered       bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`                                   // Whether the message reached its destination
	ResponsePayload []byte                 `protobuf:"bytes,2,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"` // Serialized response from destination (for request/response RPCs)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoutedMessageResponse) Reset() {
	*x = RoutedMessageResponse{}
	mi := &file_proto_robot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutedMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutedMessageResponse) ProtoMessage() {}

func (x *RoutedMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutedMessageResponse.ProtoReflect.Descriptor instead.
func (*RoutedMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{13}
}

func (x *RoutedMessageResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *RoutedMessageResponse) GetResponsePayload() []byte {
	if x != nil {
		return x.ResponsePayload
	}
	return nil
}

type VoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   int64                  `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	mi := &file_proto_robot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{14}
}

func (x *VoteRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *VoteRequest) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *VoteRequest) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_proto_robot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{15}
}

func (x *VoteResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type RaftLogEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Term            int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Command         []byte                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	LogType         string                 `protobuf:"bytes,3,opt,name=log_type,json=logType,proto3" json:"log_type,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RaftLogEntry) Reset() {
	*x = RaftLogEntry{}
	mi := &file_proto_robot_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaftLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftLogEntry) ProtoMessage() {}

func (x *RaftLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftLogEntry.ProtoReflect.Descriptor instead.
func (*RaftLogEntry) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{16}
}

func (x *RaftLogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RaftLogEntry) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RaftLogEntry) GetLogType() string {
	if x != nil {
		return x.LogType
	}
	return ""
}

func (x *RaftLogEntry) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  int64                  `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   int64                  `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       []*RaftLogEntry        `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int64                  `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_proto_robot_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{17}
}

func (x *AppendEntriesRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesRequest) GetPrevLogIndex() int64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() int64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*RaftLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() int64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_proto_robot_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_robot_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_robot_proto_rawDescGZIP(), []int{18}
}

func (x *AppendEntriesResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_robot_proto protoreflect.FileDescriptor

const file_proto_robot_proto_rawDesc = "" +
	"\n" +
	"\x11proto/robot.proto\x12\x05swarm\"\x87\x01\n" +
	"\vMoveRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\x19\n" +
	"\btarget_x\x18\x02 \x01(\x01R\atargetX\x12\x19\n" +
	"\btarget_y\x18\x03 \x01(\x01R\atargetY\x12'\n" +
	"\x0fdesired_heading\x18\x04 \x01(\x01R\x0edesiredHeading\"(\n" +
	"\fMoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\rSensorRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\"L\n" +
	"\n" +
	"ObjectData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"=\n" +
	"\x0eSensorResponse\x12+\n" +
	"\aobjects\x18\x01 \x03(\v2\x11.swarm.ObjectDataR\aobjects\"+\n" +
	"\x0eNetworkRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\"\x8f\x01\n" +
	"\vNetworkData\x12&\n" +
	"\x0ftarget_robot_id\x18\x01 \x01(\tR\rtargetRobotId\x12\x1c\n" +
	"\tbandwidth\x18\x02 \x01(\x01R\tbandwidth\x12\x18\n" +
	"\alatency\x18\x03 \x01(\x01R\alatency\x12 \n" +
	"\vreliability\x18\x04 \x01(\x01R\vreliability\"\x81\x01\n" +
	"\x0fNetworkResponse\x12A\n" +
	"\x12network_conditions\x18\x01 \x03(\v2\x12.swarm.NetworkDataR\x11networkConditions\x12+\n" +
	"\x11simulation_paused\x18\x02 \x01(\bR\x10simulationPaused\"\x8b\x01\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x01R\aheading\x12&\n" +
	"\x0fknown_leader_id\x18\x05 \x01(\tR\rknownLeaderId\"c\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x01R\aheading\"m\n" +
	"\x0fPeerSyncRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12#\n" +
	"\rlamport_clock\x18\x03 \x01(\x03R\flamportClock\".\n" +
	"\x10PeerSyncResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\"\xa9\x01\n" +
	"\x14RoutedMessageRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12%\n" +
	"\x0edestination_id\x18\x02 \x01(\tR\rdestinationId\x12!\n" +
	"\fmessage_type\x18\x03 \x01(\tR\vmessageType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x10\n" +
	"\x03ttl\x18\x05 \x01(\x05R\x03ttl\"`\n" +
	"\x15RoutedMessageResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12)\n" +
	"\x10response_payload\x18\x02 \x01(\fR\x0fresponsePayload\"\x8e\x01\n" +
	"\vVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x03R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x03R\vlastLogTerm\"E\n" +
	"\fVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12!\n" +
	"\fvote_granted\x18\x02 \x01(\bR\vvoteGranted\"\x83\x01\n" +
	"\fRaftLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\acommand\x18\x02 \x01(\fR\acommand\x12\x19\n" +
	"\blog_type\x18\x03 \x01(\tR\alogType\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs\"\xe5\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x03R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x03R\vprevLogTerm\x12-\n" +
	"\aentries\x18\x05 \x03(\v2\x13.swarm.RaftLogEntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x03R\fleaderCommit\"E\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x8c\x02\n" +
	"\fRobotService\x129\n" +
	"\x0eMoveToPosition\x12\x12.swarm.MoveRequest\x1a\x13.swarm.MoveResponse\x12<\n" +
	"\rGetSensorData\x12\x14.swarm.SensorRequest\x1a\x15.swarm.SensorResponse\x12?\n" +
	"\x0eGetNetworkData\x12\x15.swarm.NetworkRequest\x1a\x16.swarm.NetworkResponse\x12B\n" +
	"\rSendHeartbeat\x12\x17.swarm.HeartbeatRequest\x1a\x18.swarm.HeartbeatResponse2\x95\x01\n" +
	"\vPeerService\x12;\n" +
	"\bSyncData\x12\x16.swarm.PeerSyncRequest\x1a\x17.swarm.PeerSyncResponse\x12I\n" +
	"\fRouteMessage\x12\x1b.swarm.RoutedMessageRequest\x1a\x1c.swarm.RoutedMessageResponse2\x91\x01\n" +
	"\vRaftService\x126\n" +
	"\vRequestVote\x12\x12.swarm.VoteRequest\x1a\x13.swarm.VoteResponse\x12J\n" +
	"\rAppendEntries\x12\x1b.swarm.AppendEntriesRequest\x1a\x1c.swarm.AppendEntriesResponseB>Z<github.com/yihre/swarm-project/communications;communicationsb\x06proto3"

var (
	file_proto_robot_proto_rawDescOnce sync.Once
	file_proto_robot_proto_rawDescData []byte
)

func file_proto_robot_proto_rawDescGZIP() []byte {
	file_proto_robot_proto_rawDescOnce.Do(func() {
		file_proto_robot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_robot_proto_rawDesc), len(file_proto_robot_proto_rawDesc)))
	})
	return file_proto_robot_proto_rawDescData
}

var file_proto_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_robot_proto_goTypes = []any{
	(*MoveRequest)(nil),           // 0: swarm.MoveRequest
	(*MoveResponse)(nil),          // 1: swarm.MoveResponse
	(*SensorRequest)(nil),         // 2: swarm.SensorRequest
	(*ObjectData)(nil),            // 3: swarm.ObjectData
	(*SensorResponse)(nil),        // 4: swarm.SensorResponse
	(*NetworkRequest)(nil),        // 5: swarm.NetworkRequest
	(*NetworkData)(nil),           // 6: swarm.NetworkData
	(*NetworkResponse)(nil),       // 7: swarm.NetworkResponse
	(*HeartbeatRequest)(nil),      // 8: swarm.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 9: swarm.HeartbeatResponse
	(*PeerSyncRequest)(nil),       // 10: swarm.PeerSyncRequest
	(*PeerSyncResponse)(nil),      // 11: swarm.PeerSyncResponse
	(*RoutedMessageRequest)(nil),  // 12: swarm.RoutedMessageRequest
	(*RoutedMessageResponse)(nil), // 13: swarm.RoutedMessageResponse
	(*VoteRequest)(nil),           // 14: swarm.VoteRequest
	(*VoteResponse)(nil),          // 15: swarm.VoteResponse
	(*RaftLogEntry)(nil),          // 16: swarm.RaftLogEntry
	(*AppendEntriesRequest)(nil),  // 17: swarm.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 18: swarm.AppendEntriesResponse
}
var file_proto_robot_proto_depIdxs = []int32{
	3,  // 0: swarm.SensorResponse.objects:type_name -> swarm.ObjectData
	6,  // 1: swarm.NetworkResponse.network_conditions:type_name -> swarm.NetworkData
	16, // 2: swarm.AppendEntriesRequest.entries:type_name -> swarm.RaftLogEntry
	0,  // 3: swarm.RobotService.MoveToPosition:input_type -> swarm.MoveRequest
	2,  // 4: swarm.RobotService.GetSensorData:input_type -> swarm.SensorRequest
	5,  // 5: swarm.RobotService.GetNetworkData:input_type -> swarm.NetworkRequest
	8,  // 6: swarm.RobotService.SendHeartbeat:input_type -> swarm.HeartbeatRequest
	10, // 7: swarm.PeerService.SyncData:input_type -> swarm.PeerSyncRequest
	12, // 8: swarm.PeerService.RouteMessage:input_type -> swarm.RoutedMessageRequest
	14, // 9: swarm.RaftService.RequestVote:input_type -> swarm.VoteRequest
	17, // 10: swarm.RaftService.AppendEntries:input_type -> swarm.AppendEntriesRequest
	1,  // 11: swarm.RobotService.MoveToPosition:output_type -> swarm.MoveResponse
	4,  // 12: swarm.RobotService.GetSensorData:output_type -> swarm.SensorResponse
	7,  // 13: swarm.RobotService.GetNetworkData:output_type -> swarm.NetworkResponse
	9,  // 14: swarm.RobotService.SendHeartbeat:output_type -> swarm.HeartbeatResponse
	11, // 15: swarm.PeerService.SyncData:output_type -> swarm.PeerSyncResponse
	13, // 16: swarm.PeerService.RouteMessage:output_type -> swarm.RoutedMessageResponse
	15, // 17: swarm.RaftService.RequestVote:output_type -> swarm.VoteResponse
	18, // 18: swarm.RaftService.AppendEntries:output_type -> swarm.AppendEntriesResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_robot_proto_init() }
func file_proto_robot_proto_init() {
	if File_proto_robot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_robot_proto_rawDesc), len(file_proto_robot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_robot_proto_goTypes,
		DependencyIndexes: file_proto_robot_proto_depIdxs,
		MessageInfos:      file_proto_robot_proto_msgTypes,
	}.Build()
	File_proto_robot_proto = out.File
	file_proto_robot_proto_goTypes = nil
	file_proto_robot_proto_depIdxs = nil
}
