// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: robot.proto

package communications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoveRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	RobotId string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	// Position or direction
	X             float64 `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64 `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Velocity      float64 `protobuf:"fixed64,4,opt,name=velocity,proto3" json:"velocity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	mi := &file_robot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{0}
}

func (x *MoveRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *MoveRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MoveRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MoveRequest) GetVelocity() float64 {
	if x != nil {
		return x.Velocity
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	mi := &file_robot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{1}
}

func (x *MoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SensorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorRequest) Reset() {
	*x = SensorRequest{}
	mi := &file_robot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorRequest) ProtoMessage() {}

func (x *SensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorRequest.ProtoReflect.Descriptor instead.
func (*SensorRequest) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{2}
}

func (x *SensorRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type ObjectData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectData) Reset() {
	*x = ObjectData{}
	mi := &file_robot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectData) ProtoMessage() {}

func (x *ObjectData) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectData.ProtoReflect.Descriptor instead.
func (*ObjectData) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectData) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ObjectData) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ObjectData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type SensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*ObjectData          `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorResponse) Reset() {
	*x = SensorResponse{}
	mi := &file_robot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorResponse) ProtoMessage() {}

func (x *SensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorResponse.ProtoReflect.Descriptor instead.
func (*SensorResponse) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{4}
}

func (x *SensorResponse) GetObjects() []*ObjectData {
	if x != nil {
		return x.Objects
	}
	return nil
}

type NetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkRequest) Reset() {
	*x = NetworkRequest{}
	mi := &file_robot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkRequest) ProtoMessage() {}

func (x *NetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkRequest.ProtoReflect.Descriptor instead.
func (*NetworkRequest) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{5}
}

func (x *NetworkRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type NetworkData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetRobotId string                 `protobuf:"bytes,1,opt,name=target_robot_id,json=targetRobotId,proto3" json:"target_robot_id,omitempty"`
	Bandwidth     float64                `protobuf:"fixed64,2,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Latency       float64                `protobuf:"fixed64,3,opt,name=latency,proto3" json:"latency,omitempty"`
	Reliability   float64                `protobuf:"fixed64,4,opt,name=reliability,proto3" json:"reliability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkData) Reset() {
	*x = NetworkData{}
	mi := &file_robot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkData) ProtoMessage() {}

func (x *NetworkData) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkData.ProtoReflect.Descriptor instead.
func (*NetworkData) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkData) GetTargetRobotId() string {
	if x != nil {
		return x.TargetRobotId
	}
	return ""
}

func (x *NetworkData) GetBandwidth() float64 {
	if x != nil {
		return x.Bandwidth
	}
	return 0
}

func (x *NetworkData) GetLatency() float64 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *NetworkData) GetReliability() float64 {
	if x != nil {
		return x.Reliability
	}
	return 0
}

type NetworkResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NetworkConditions []*NetworkData         `protobuf:"bytes,1,rep,name=network_conditions,json=networkConditions,proto3" json:"network_conditions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetworkResponse) Reset() {
	*x = NetworkResponse{}
	mi := &file_robot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkResponse) ProtoMessage() {}

func (x *NetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkResponse.ProtoReflect.Descriptor instead.
func (*NetworkResponse) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkResponse) GetNetworkConditions() []*NetworkData {
	if x != nil {
		return x.NetworkConditions
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       string                 `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Heading       float64                `protobuf:"fixed64,4,opt,name=heading,proto3" json:"heading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_robot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *HeartbeatRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *HeartbeatRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *HeartbeatRequest) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_robot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PeerSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // For simulating large payloads (e.g. map sync)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerSyncRequest) Reset() {
	*x = PeerSyncRequest{}
	mi := &file_robot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSyncRequest) ProtoMessage() {}

func (x *PeerSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSyncRequest.ProtoReflect.Descriptor instead.
func (*PeerSyncRequest) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{10}
}

func (x *PeerSyncRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *PeerSyncRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PeerSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerSyncResponse) Reset() {
	*x = PeerSyncResponse{}
	mi := &file_robot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSyncResponse) ProtoMessage() {}

func (x *PeerSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_robot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSyncResponse.ProtoReflect.Descriptor instead.
func (*PeerSyncResponse) Descriptor() ([]byte, []int) {
	return file_robot_proto_rawDescGZIP(), []int{11}
}

func (x *PeerSyncResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

var File_robot_proto protoreflect.FileDescriptor

const file_robot_proto_rawDesc = "" +
	"\n" +
	"\vrobot.proto\x12\x05swarm\"`\n" +
	"\vMoveRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x1a\n" +
	"\bvelocity\x18\x04 \x01(\x01R\bvelocity\"(\n" +
	"\fMoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"*\n" +
	"\rSensorRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\"L\n" +
	"\n" +
	"ObjectData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"=\n" +
	"\x0eSensorResponse\x12+\n" +
	"\aobjects\x18\x01 \x03(\v2\x11.swarm.ObjectDataR\aobjects\"+\n" +
	"\x0eNetworkRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\"\x8f\x01\n" +
	"\vNetworkData\x12&\n" +
	"\x0ftarget_robot_id\x18\x01 \x01(\tR\rtargetRobotId\x12\x1c\n" +
	"\tbandwidth\x18\x02 \x01(\x01R\tbandwidth\x12\x18\n" +
	"\alatency\x18\x03 \x01(\x01R\alatency\x12 \n" +
	"\vreliability\x18\x04 \x01(\x01R\vreliability\"T\n" +
	"\x0fNetworkResponse\x12A\n" +
	"\x12network_conditions\x18\x01 \x03(\v2\x12.swarm.NetworkDataR\x11networkConditions\"c\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x01R\aheading\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\x0fPeerSyncRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\".\n" +
	"\x10PeerSyncResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived2\x8c\x02\n" +
	"\fRobotService\x129\n" +
	"\x0eMoveToPosition\x12\x12.swarm.MoveRequest\x1a\x13.swarm.MoveResponse\x12<\n" +
	"\rGetSensorData\x12\x14.swarm.SensorRequest\x1a\x15.swarm.SensorResponse\x12?\n" +
	"\x0eGetNetworkData\x12\x15.swarm.NetworkRequest\x1a\x16.swarm.NetworkResponse\x12B\n" +
	"\rSendHeartbeat\x12\x17.swarm.HeartbeatRequest\x1a\x18.swarm.HeartbeatResponse2J\n" +
	"\vPeerService\x12;\n" +
	"\bSyncData\x12\x16.swarm.PeerSyncRequest\x1a\x17.swarm.PeerSyncResponseB>Z<github.com/yihre/swarm-project/communications;communicationsb\x06proto3"

var (
	file_robot_proto_rawDescOnce sync.Once
	file_robot_proto_rawDescData []byte
)

func file_robot_proto_rawDescGZIP() []byte {
	file_robot_proto_rawDescOnce.Do(func() {
		file_robot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_robot_proto_rawDesc), len(file_robot_proto_rawDesc)))
	})
	return file_robot_proto_rawDescData
}

var file_robot_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_robot_proto_goTypes = []any{
	(*MoveRequest)(nil),       // 0: swarm.MoveRequest
	(*MoveResponse)(nil),      // 1: swarm.MoveResponse
	(*SensorRequest)(nil),     // 2: swarm.SensorRequest
	(*ObjectData)(nil),        // 3: swarm.ObjectData
	(*SensorResponse)(nil),    // 4: swarm.SensorResponse
	(*NetworkRequest)(nil),    // 5: swarm.NetworkRequest
	(*NetworkData)(nil),       // 6: swarm.NetworkData
	(*NetworkResponse)(nil),   // 7: swarm.NetworkResponse
	(*HeartbeatRequest)(nil),  // 8: swarm.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 9: swarm.HeartbeatResponse
	(*PeerSyncRequest)(nil),   // 10: swarm.PeerSyncRequest
	(*PeerSyncResponse)(nil),  // 11: swarm.PeerSyncResponse
}
var file_robot_proto_depIdxs = []int32{
	3,  // 0: swarm.SensorResponse.objects:type_name -> swarm.ObjectData
	6,  // 1: swarm.NetworkResponse.network_conditions:type_name -> swarm.NetworkData
	0,  // 2: swarm.RobotService.MoveToPosition:input_type -> swarm.MoveRequest
	2,  // 3: swarm.RobotService.GetSensorData:input_type -> swarm.SensorRequest
	5,  // 4: swarm.RobotService.GetNetworkData:input_type -> swarm.NetworkRequest
	8,  // 5: swarm.RobotService.SendHeartbeat:input_type -> swarm.HeartbeatRequest
	10, // 6: swarm.PeerService.SyncData:input_type -> swarm.PeerSyncRequest
	1,  // 7: swarm.RobotService.MoveToPosition:output_type -> swarm.MoveResponse
	4,  // 8: swarm.RobotService.GetSensorData:output_type -> swarm.SensorResponse
	7,  // 9: swarm.RobotService.GetNetworkData:output_type -> swarm.NetworkResponse
	9,  // 10: swarm.RobotService.SendHeartbeat:output_type -> swarm.HeartbeatResponse
	11, // 11: swarm.PeerService.SyncData:output_type -> swarm.PeerSyncResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_robot_proto_init() }
func file_robot_proto_init() {
	if File_robot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_robot_proto_rawDesc), len(file_robot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_robot_proto_goTypes,
		DependencyIndexes: file_robot_proto_depIdxs,
		MessageInfos:      file_robot_proto_msgTypes,
	}.Build()
	File_robot_proto = out.File
	file_robot_proto_goTypes = nil
	file_robot_proto_depIdxs = nil
}
