// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: proto/visualiser.proto

package communications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentRequest) Reset() {
	*x = EnvironmentRequest{}
	mi := &file_proto_visualiser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentRequest) ProtoMessage() {}

func (x *EnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_visualiser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentRequest.ProtoReflect.Descriptor instead.
func (*EnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_visualiser_proto_rawDescGZIP(), []int{0}
}

type EnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         float64                `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	Obstacles     []*Obstacle            `protobuf:"bytes,3,rep,name=obstacles,proto3" json:"obstacles,omitempty"`
	IsPaused      bool                   `protobuf:"varint,4,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentResponse) Reset() {
	*x = EnvironmentResponse{}
	mi := &file_proto_visualiser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentResponse) ProtoMessage() {}

func (x *EnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_visualiser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentResponse.ProtoReflect.Descriptor instead.
func (*EnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_visualiser_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentResponse) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *EnvironmentResponse) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *EnvironmentResponse) GetObstacles() []*Obstacle {
	if x != nil {
		return x.Obstacles
	}
	return nil
}

func (x *EnvironmentResponse) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

type SimulationPauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pause         bool                   `protobuf:"varint,1,opt,name=pause,proto3" json:"pause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationPauseRequest) Reset() {
	*x = SimulationPauseRequest{}
	mi := &file_proto_visualiser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationPauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationPauseRequest) ProtoMessage() {}

func (x *SimulationPauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_visualiser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationPauseRequest.ProtoReflect.Descriptor instead.
func (*SimulationPauseRequest) Descriptor() ([]byte, []int) {
	return file_proto_visualiser_proto_rawDescGZIP(), []int{2}
}

func (x *SimulationPauseRequest) GetPause() bool {
	if x != nil {
		return x.Pause
	}
	return false
}

type SimulationPauseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsPaused      bool                   `protobuf:"varint,2,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationPauseResponse) Reset() {
	*x = SimulationPauseResponse{}
	mi := &file_proto_visualiser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationPauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationPauseResponse) ProtoMessage() {}

func (x *SimulationPauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_visualiser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationPauseResponse.ProtoReflect.Descriptor instead.
func (*SimulationPauseResponse) Descriptor() ([]byte, []int) {
	return file_proto_visualiser_proto_rawDescGZIP(), []int{3}
}

func (x *SimulationPauseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SimulationPauseResponse) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

type Obstacle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Width         float64                `protobuf:"fixed64,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Obstacle) Reset() {
	*x = Obstacle{}
	mi := &file_proto_visualiser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Obstacle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obstacle) ProtoMessage() {}

func (x *Obstacle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_visualiser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obstacle.ProtoReflect.Descriptor instead.
func (*Obstacle) Descriptor() ([]byte, []int) {
	return file_proto_visualiser_proto_rawDescGZIP(), []int{4}
}

func (x *Obstacle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Obstacle) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Obstacle) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Obstacle) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Obstacle) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type RobotDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotDataRequest) Reset() {
	*x = RobotDataRequest{}
	mi := &file_proto_visualiser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotDataRequest) ProtoMessage() {}

func (x *RobotDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_visualiser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotDataRequest.ProtoReflect.Descriptor instead.
func (*RobotDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_visualiser_proto_rawDescGZIP(), []int{5}
}

type RobotInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X                  float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                  float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Heading            float64                `protobuf:"fixed64,4,opt,name=heading,proto3" json:"heading,omitempty"`
	IsLeader           bool                   `protobuf:"varint,5,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	CommunicationRange float64                `protobuf:"fixed64,6,opt,name=communication_range,json=communicationRange,proto3" json:"communication_range,omitempty"`
	InRangePeerIds     []string               `protobuf:"bytes,7,rep,name=in_range_peer_ids,json=inRangePeerIds,proto3" json:"in_range_peer_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RobotInfo) Reset() {
	*x = RobotInfo{}
	mi := &file_proto_visualiser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotInfo) ProtoMessage() {}

func (x *RobotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_visualiser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotInfo.ProtoReflect.Descriptor instead.
func (*RobotInfo) Descriptor() ([]byte, []int) {
	return file_proto_visualiser_proto_rawDescGZIP(), []int{6}
}

func (x *RobotInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RobotInfo) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RobotInfo) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RobotInfo) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *RobotInfo) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *RobotInfo) GetCommunicationRange() float64 {
	if x != nil {
		return x.CommunicationRange
	}
	return 0
}

func (x *RobotInfo) GetInRangePeerIds() []string {
	if x != nil {
		return x.InRangePeerIds
	}
	return nil
}

type RobotDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Robots        []*RobotInfo           `protobuf:"bytes,1,rep,name=robots,proto3" json:"robots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotDataResponse) Reset() {
	*x = RobotDataResponse{}
	mi := &file_proto_visualiser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotDataResponse) ProtoMessage() {}

func (x *RobotDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_visualiser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotDataResponse.ProtoReflect.Descriptor instead.
func (*RobotDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_visualiser_proto_rawDescGZIP(), []int{7}
}

func (x *RobotDataResponse) GetRobots() []*RobotInfo {
	if x != nil {
		return x.Robots
	}
	return nil
}

var File_proto_visualiser_proto protoreflect.FileDescriptor

const file_proto_visualiser_proto_rawDesc = "" +
	"\n" +
	"\x16proto/visualiser.proto\x12\x05swarm\"\x14\n" +
	"\x12EnvironmentRequest\"\x8f\x01\n" +
	"\x13EnvironmentResponse\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x01R\x06height\x12-\n" +
	"\tobstacles\x18\x03 \x03(\v2\x0f.swarm.ObstacleR\tobstacles\x12\x1b\n" +
	"\tis_paused\x18\x04 \x01(\bR\bisPaused\".\n" +
	"\x16SimulationPauseRequest\x12\x14\n" +
	"\x05pause\x18\x01 \x01(\bR\x05pause\"P\n" +
	"\x17SimulationPauseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tis_paused\x18\x02 \x01(\bR\bisPaused\"d\n" +
	"\bObstacle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x01R\x06height\"\x12\n" +
	"\x10RobotDataRequest\"\xca\x01\n" +
	"\tRobotInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x01R\aheading\x12\x1b\n" +
	"\tis_leader\x18\x05 \x01(\bR\bisLeader\x12/\n" +
	"\x13communication_range\x18\x06 \x01(\x01R\x12communicationRange\x12)\n" +
	"\x11in_range_peer_ids\x18\a \x03(\tR\x0einRangePeerIds\"=\n" +
	"\x11RobotDataResponse\x12(\n" +
	"\x06robots\x18\x01 \x03(\v2\x10.swarm.RobotInfoR\x06robots2\xf8\x01\n" +
	"\x11VisualiserService\x12K\n" +
	"\x12GetEnvironmentData\x12\x19.swarm.EnvironmentRequest\x1a\x1a.swarm.EnvironmentResponse\x12A\n" +
	"\fGetRobotData\x12\x17.swarm.RobotDataRequest\x1a\x18.swarm.RobotDataResponse\x12S\n" +
	"\x12SetSimulationPause\x12\x1d.swarm.SimulationPauseRequest\x1a\x1e.swarm.SimulationPauseResponseB>Z<github.com/yihre/swarm-project/communications;communicationsb\x06proto3"

var (
	file_proto_visualiser_proto_rawDescOnce sync.Once
	file_proto_visualiser_proto_rawDescData []byte
)

func file_proto_visualiser_proto_rawDescGZIP() []byte {
	file_proto_visualiser_proto_rawDescOnce.Do(func() {
		file_proto_visualiser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_visualiser_proto_rawDesc), len(file_proto_visualiser_proto_rawDesc)))
	})
	return file_proto_visualiser_proto_rawDescData
}

var file_proto_visualiser_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_visualiser_proto_goTypes = []any{
	(*EnvironmentRequest)(nil),      // 0: swarm.EnvironmentRequest
	(*EnvironmentResponse)(nil),     // 1: swarm.EnvironmentResponse
	(*SimulationPauseRequest)(nil),  // 2: swarm.SimulationPauseRequest
	(*SimulationPauseResponse)(nil), // 3: swarm.SimulationPauseResponse
	(*Obstacle)(nil),                // 4: swarm.Obstacle
	(*RobotDataRequest)(nil),        // 5: swarm.RobotDataRequest
	(*RobotInfo)(nil),               // 6: swarm.RobotInfo
	(*RobotDataResponse)(nil),       // 7: swarm.RobotDataResponse
}
var file_proto_visualiser_proto_depIdxs = []int32{
	4, // 0: swarm.EnvironmentResponse.obstacles:type_name -> swarm.Obstacle
	6, // 1: swarm.RobotDataResponse.robots:type_name -> swarm.RobotInfo
	0, // 2: swarm.VisualiserService.GetEnvironmentData:input_type -> swarm.EnvironmentRequest
	5, // 3: swarm.VisualiserService.GetRobotData:input_type -> swarm.RobotDataRequest
	2, // 4: swarm.VisualiserService.SetSimulationPause:input_type -> swarm.SimulationPauseRequest
	1, // 5: swarm.VisualiserService.GetEnvironmentData:output_type -> swarm.EnvironmentResponse
	7, // 6: swarm.VisualiserService.GetRobotData:output_type -> swarm.RobotDataResponse
	3, // 7: swarm.VisualiserService.SetSimulationPause:output_type -> swarm.SimulationPauseResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_visualiser_proto_init() }
func file_proto_visualiser_proto_init() {
	if File_proto_visualiser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_visualiser_proto_rawDesc), len(file_proto_visualiser_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_visualiser_proto_goTypes,
		DependencyIndexes: file_proto_visualiser_proto_depIdxs,
		MessageInfos:      file_proto_visualiser_proto_msgTypes,
	}.Build()
	File_proto_visualiser_proto = out.File
	file_proto_visualiser_proto_goTypes = nil
	file_proto_visualiser_proto_depIdxs = nil
}
