// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0--rc2
// source: visualiser.proto

package communications

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaderLogStatus int32

const (
	LeaderLogStatus_LEADER_LOG_STATUS_UNSPECIFIED          LeaderLogStatus = 0
	LeaderLogStatus_LEADER_LOG_STATUS_PENDING_CONFIRMATION LeaderLogStatus = 1
	LeaderLogStatus_LEADER_LOG_STATUS_CONFIRMED            LeaderLogStatus = 2
)

// Enum value maps for LeaderLogStatus.
var (
	LeaderLogStatus_name = map[int32]string{
		0: "LEADER_LOG_STATUS_UNSPECIFIED",
		1: "LEADER_LOG_STATUS_PENDING_CONFIRMATION",
		2: "LEADER_LOG_STATUS_CONFIRMED",
	}
	LeaderLogStatus_value = map[string]int32{
		"LEADER_LOG_STATUS_UNSPECIFIED":          0,
		"LEADER_LOG_STATUS_PENDING_CONFIRMATION": 1,
		"LEADER_LOG_STATUS_CONFIRMED":            2,
	}
)

func (x LeaderLogStatus) Enum() *LeaderLogStatus {
	p := new(LeaderLogStatus)
	*p = x
	return p
}

func (x LeaderLogStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LeaderLogStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_visualiser_proto_enumTypes[0].Descriptor()
}

func (LeaderLogStatus) Type() protoreflect.EnumType {
	return &file_visualiser_proto_enumTypes[0]
}

func (x LeaderLogStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LeaderLogStatus.Descriptor instead.
func (LeaderLogStatus) EnumDescriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{0}
}

type EnvironmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentRequest) Reset() {
	*x = EnvironmentRequest{}
	mi := &file_visualiser_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentRequest) ProtoMessage() {}

func (x *EnvironmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentRequest.ProtoReflect.Descriptor instead.
func (*EnvironmentRequest) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{0}
}

type EnvironmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         float64                `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
	Obstacles     []*Obstacle            `protobuf:"bytes,3,rep,name=obstacles,proto3" json:"obstacles,omitempty"`
	IsPaused      bool                   `protobuf:"varint,4,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvironmentResponse) Reset() {
	*x = EnvironmentResponse{}
	mi := &file_visualiser_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvironmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvironmentResponse) ProtoMessage() {}

func (x *EnvironmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvironmentResponse.ProtoReflect.Descriptor instead.
func (*EnvironmentResponse) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{1}
}

func (x *EnvironmentResponse) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *EnvironmentResponse) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *EnvironmentResponse) GetObstacles() []*Obstacle {
	if x != nil {
		return x.Obstacles
	}
	return nil
}

func (x *EnvironmentResponse) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

type SimulationPauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pause         bool                   `protobuf:"varint,1,opt,name=pause,proto3" json:"pause,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationPauseRequest) Reset() {
	*x = SimulationPauseRequest{}
	mi := &file_visualiser_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationPauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationPauseRequest) ProtoMessage() {}

func (x *SimulationPauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationPauseRequest.ProtoReflect.Descriptor instead.
func (*SimulationPauseRequest) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{2}
}

func (x *SimulationPauseRequest) GetPause() bool {
	if x != nil {
		return x.Pause
	}
	return false
}

type SimulationPauseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	IsPaused      bool                   `protobuf:"varint,2,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulationPauseResponse) Reset() {
	*x = SimulationPauseResponse{}
	mi := &file_visualiser_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulationPauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulationPauseResponse) ProtoMessage() {}

func (x *SimulationPauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulationPauseResponse.ProtoReflect.Descriptor instead.
func (*SimulationPauseResponse) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{3}
}

func (x *SimulationPauseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SimulationPauseResponse) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

type Obstacle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Width         float64                `protobuf:"fixed64,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        float64                `protobuf:"fixed64,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Obstacle) Reset() {
	*x = Obstacle{}
	mi := &file_visualiser_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Obstacle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obstacle) ProtoMessage() {}

func (x *Obstacle) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obstacle.ProtoReflect.Descriptor instead.
func (*Obstacle) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{4}
}

func (x *Obstacle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Obstacle) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Obstacle) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Obstacle) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Obstacle) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type RobotDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotDataRequest) Reset() {
	*x = RobotDataRequest{}
	mi := &file_visualiser_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotDataRequest) ProtoMessage() {}

func (x *RobotDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotDataRequest.ProtoReflect.Descriptor instead.
func (*RobotDataRequest) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{5}
}

type RobotInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X                  float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                  float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Heading            float64                `protobuf:"fixed64,4,opt,name=heading,proto3" json:"heading,omitempty"`
	IsLeader           bool                   `protobuf:"varint,5,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	CommunicationRange float64                `protobuf:"fixed64,6,opt,name=communication_range,json=communicationRange,proto3" json:"communication_range,omitempty"`
	InRangePeerIds     []string               `protobuf:"bytes,7,rep,name=in_range_peer_ids,json=inRangePeerIds,proto3" json:"in_range_peer_ids,omitempty"`
	RaftTerm           int64                  `protobuf:"varint,8,opt,name=raft_term,json=raftTerm,proto3" json:"raft_term,omitempty"`
	RaftLogIndex       int64                  `protobuf:"varint,9,opt,name=raft_log_index,json=raftLogIndex,proto3" json:"raft_log_index,omitempty"`
	CommitIndex        int64                  `protobuf:"varint,10,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RobotInfo) Reset() {
	*x = RobotInfo{}
	mi := &file_visualiser_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotInfo) ProtoMessage() {}

func (x *RobotInfo) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotInfo.ProtoReflect.Descriptor instead.
func (*RobotInfo) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{6}
}

func (x *RobotInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RobotInfo) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RobotInfo) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RobotInfo) GetHeading() float64 {
	if x != nil {
		return x.Heading
	}
	return 0
}

func (x *RobotInfo) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *RobotInfo) GetCommunicationRange() float64 {
	if x != nil {
		return x.CommunicationRange
	}
	return 0
}

func (x *RobotInfo) GetInRangePeerIds() []string {
	if x != nil {
		return x.InRangePeerIds
	}
	return nil
}

func (x *RobotInfo) GetRaftTerm() int64 {
	if x != nil {
		return x.RaftTerm
	}
	return 0
}

func (x *RobotInfo) GetRaftLogIndex() int64 {
	if x != nil {
		return x.RaftLogIndex
	}
	return 0
}

func (x *RobotInfo) GetCommitIndex() int64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

type RobotDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Robots        []*RobotInfo           `protobuf:"bytes,1,rep,name=robots,proto3" json:"robots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotDataResponse) Reset() {
	*x = RobotDataResponse{}
	mi := &file_visualiser_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotDataResponse) ProtoMessage() {}

func (x *RobotDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotDataResponse.ProtoReflect.Descriptor instead.
func (*RobotDataResponse) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{7}
}

func (x *RobotDataResponse) GetRobots() []*RobotInfo {
	if x != nil {
		return x.Robots
	}
	return nil
}

type LeaderLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderLogRequest) Reset() {
	*x = LeaderLogRequest{}
	mi := &file_visualiser_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderLogRequest) ProtoMessage() {}

func (x *LeaderLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderLogRequest.ProtoReflect.Descriptor instead.
func (*LeaderLogRequest) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{8}
}

type LeaderLogEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentLeader   string                 `protobuf:"bytes,1,opt,name=current_leader,json=currentLeader,proto3" json:"current_leader,omitempty"`
	Term            int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	Index           int64                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Status          LeaderLogStatus        `protobuf:"varint,5,opt,name=status,proto3,enum=swarm.LeaderLogStatus" json:"status,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,6,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LeaderLogEntry) Reset() {
	*x = LeaderLogEntry{}
	mi := &file_visualiser_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderLogEntry) ProtoMessage() {}

func (x *LeaderLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderLogEntry.ProtoReflect.Descriptor instead.
func (*LeaderLogEntry) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{9}
}

func (x *LeaderLogEntry) GetCurrentLeader() string {
	if x != nil {
		return x.CurrentLeader
	}
	return ""
}

func (x *LeaderLogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LeaderLogEntry) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LeaderLogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LeaderLogEntry) GetStatus() LeaderLogStatus {
	if x != nil {
		return x.Status
	}
	return LeaderLogStatus_LEADER_LOG_STATUS_UNSPECIFIED
}

func (x *LeaderLogEntry) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type LeaderLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentLeader string                 `protobuf:"bytes,1,opt,name=current_leader,json=currentLeader,proto3" json:"current_leader,omitempty"`
	CurrentTerm   int64                  `protobuf:"varint,2,opt,name=current_term,json=currentTerm,proto3" json:"current_term,omitempty"`
	Entries       []*LeaderLogEntry      `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderLogResponse) Reset() {
	*x = LeaderLogResponse{}
	mi := &file_visualiser_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderLogResponse) ProtoMessage() {}

func (x *LeaderLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderLogResponse.ProtoReflect.Descriptor instead.
func (*LeaderLogResponse) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{10}
}

func (x *LeaderLogResponse) GetCurrentLeader() string {
	if x != nil {
		return x.CurrentLeader
	}
	return ""
}

func (x *LeaderLogResponse) GetCurrentTerm() int64 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *LeaderLogResponse) GetEntries() []*LeaderLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type KillRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional. If set, the world removes the matching robot instead of choosing one at random.
	RobotId       string `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillRequest) Reset() {
	*x = KillRequest{}
	mi := &file_visualiser_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillRequest) ProtoMessage() {}

func (x *KillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillRequest.ProtoReflect.Descriptor instead.
func (*KillRequest) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{11}
}

func (x *KillRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

type KillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	KilledRobotId string                 `protobuf:"bytes,2,opt,name=killed_robot_id,json=killedRobotId,proto3" json:"killed_robot_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillResponse) Reset() {
	*x = KillResponse{}
	mi := &file_visualiser_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillResponse) ProtoMessage() {}

func (x *KillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_visualiser_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillResponse.ProtoReflect.Descriptor instead.
func (*KillResponse) Descriptor() ([]byte, []int) {
	return file_visualiser_proto_rawDescGZIP(), []int{12}
}

func (x *KillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KillResponse) GetKilledRobotId() string {
	if x != nil {
		return x.KilledRobotId
	}
	return ""
}

func (x *KillResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_visualiser_proto protoreflect.FileDescriptor

const file_visualiser_proto_rawDesc = "" +
	"\n" +
	"\x10visualiser.proto\x12\x05swarm\"\x14\n" +
	"\x12EnvironmentRequest\"\x8f\x01\n" +
	"\x13EnvironmentResponse\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x01R\x06height\x12-\n" +
	"\tobstacles\x18\x03 \x03(\v2\x0f.swarm.ObstacleR\tobstacles\x12\x1b\n" +
	"\tis_paused\x18\x04 \x01(\bR\bisPaused\".\n" +
	"\x16SimulationPauseRequest\x12\x14\n" +
	"\x05pause\x18\x01 \x01(\bR\x05pause\"P\n" +
	"\x17SimulationPauseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tis_paused\x18\x02 \x01(\bR\bisPaused\"d\n" +
	"\bObstacle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x01R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x01R\x06height\"\x12\n" +
	"\x10RobotDataRequest\"\xb0\x02\n" +
	"\tRobotInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01y\x12\x18\n" +
	"\aheading\x18\x04 \x01(\x01R\aheading\x12\x1b\n" +
	"\tis_leader\x18\x05 \x01(\bR\bisLeader\x12/\n" +
	"\x13communication_range\x18\x06 \x01(\x01R\x12communicationRange\x12)\n" +
	"\x11in_range_peer_ids\x18\a \x03(\tR\x0einRangePeerIds\x12\x1b\n" +
	"\traft_term\x18\b \x01(\x03R\braftTerm\x12$\n" +
	"\x0eraft_log_index\x18\t \x01(\x03R\fraftLogIndex\x12!\n" +
	"\fcommit_index\x18\n" +
	" \x01(\x03R\vcommitIndex\"=\n" +
	"\x11RobotDataResponse\x12(\n" +
	"\x06robots\x18\x01 \x03(\v2\x10.swarm.RobotInfoR\x06robots\"\x12\n" +
	"\x10LeaderLogRequest\"\xd7\x01\n" +
	"\x0eLeaderLogEntry\x12%\n" +
	"\x0ecurrent_leader\x18\x01 \x01(\tR\rcurrentLeader\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x03R\x05index\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12.\n" +
	"\x06status\x18\x05 \x01(\x0e2\x16.swarm.LeaderLogStatusR\x06status\x12*\n" +
	"\x11timestamp_unix_ms\x18\x06 \x01(\x03R\x0ftimestampUnixMs\"\x8e\x01\n" +
	"\x11LeaderLogResponse\x12%\n" +
	"\x0ecurrent_leader\x18\x01 \x01(\tR\rcurrentLeader\x12!\n" +
	"\fcurrent_term\x18\x02 \x01(\x03R\vcurrentTerm\x12/\n" +
	"\aentries\x18\x03 \x03(\v2\x15.swarm.LeaderLogEntryR\aentries\"(\n" +
	"\vKillRequest\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\tR\arobotId\"f\n" +
	"\fKillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fkilled_robot_id\x18\x02 \x01(\tR\rkilledRobotId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*\x81\x01\n" +
	"\x0fLeaderLogStatus\x12!\n" +
	"\x1dLEADER_LOG_STATUS_UNSPECIFIED\x10\x00\x12*\n" +
	"&LEADER_LOG_STATUS_PENDING_CONFIRMATION\x10\x01\x12\x1f\n" +
	"\x1bLEADER_LOG_STATUS_CONFIRMED\x10\x022\xec\x02\n" +
	"\x11VisualiserService\x12K\n" +
	"\x12GetEnvironmentData\x12\x19.swarm.EnvironmentRequest\x1a\x1a.swarm.EnvironmentResponse\x12A\n" +
	"\fGetRobotData\x12\x17.swarm.RobotDataRequest\x1a\x18.swarm.RobotDataResponse\x12S\n" +
	"\x12SetSimulationPause\x12\x1d.swarm.SimulationPauseRequest\x1a\x1e.swarm.SimulationPauseResponse\x12A\n" +
	"\fGetLeaderLog\x12\x17.swarm.LeaderLogRequest\x1a\x18.swarm.LeaderLogResponse\x12/\n" +
	"\x04Kill\x12\x12.swarm.KillRequest\x1a\x13.swarm.KillResponseB>Z<github.com/yihre/swarm-project/communications;communicationsb\x06proto3"

var (
	file_visualiser_proto_rawDescOnce sync.Once
	file_visualiser_proto_rawDescData []byte
)

func file_visualiser_proto_rawDescGZIP() []byte {
	file_visualiser_proto_rawDescOnce.Do(func() {
		file_visualiser_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_visualiser_proto_rawDesc), len(file_visualiser_proto_rawDesc)))
	})
	return file_visualiser_proto_rawDescData
}

var file_visualiser_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_visualiser_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_visualiser_proto_goTypes = []any{
	(LeaderLogStatus)(0),            // 0: swarm.LeaderLogStatus
	(*EnvironmentRequest)(nil),      // 1: swarm.EnvironmentRequest
	(*EnvironmentResponse)(nil),     // 2: swarm.EnvironmentResponse
	(*SimulationPauseRequest)(nil),  // 3: swarm.SimulationPauseRequest
	(*SimulationPauseResponse)(nil), // 4: swarm.SimulationPauseResponse
	(*Obstacle)(nil),                // 5: swarm.Obstacle
	(*RobotDataRequest)(nil),        // 6: swarm.RobotDataRequest
	(*RobotInfo)(nil),               // 7: swarm.RobotInfo
	(*RobotDataResponse)(nil),       // 8: swarm.RobotDataResponse
	(*LeaderLogRequest)(nil),        // 9: swarm.LeaderLogRequest
	(*LeaderLogEntry)(nil),          // 10: swarm.LeaderLogEntry
	(*LeaderLogResponse)(nil),       // 11: swarm.LeaderLogResponse
	(*KillRequest)(nil),             // 12: swarm.KillRequest
	(*KillResponse)(nil),            // 13: swarm.KillResponse
}
var file_visualiser_proto_depIdxs = []int32{
	5,  // 0: swarm.EnvironmentResponse.obstacles:type_name -> swarm.Obstacle
	7,  // 1: swarm.RobotDataResponse.robots:type_name -> swarm.RobotInfo
	0,  // 2: swarm.LeaderLogEntry.status:type_name -> swarm.LeaderLogStatus
	10, // 3: swarm.LeaderLogResponse.entries:type_name -> swarm.LeaderLogEntry
	1,  // 4: swarm.VisualiserService.GetEnvironmentData:input_type -> swarm.EnvironmentRequest
	6,  // 5: swarm.VisualiserService.GetRobotData:input_type -> swarm.RobotDataRequest
	3,  // 6: swarm.VisualiserService.SetSimulationPause:input_type -> swarm.SimulationPauseRequest
	9,  // 7: swarm.VisualiserService.GetLeaderLog:input_type -> swarm.LeaderLogRequest
	12, // 8: swarm.VisualiserService.Kill:input_type -> swarm.KillRequest
	2,  // 9: swarm.VisualiserService.GetEnvironmentData:output_type -> swarm.EnvironmentResponse
	8,  // 10: swarm.VisualiserService.GetRobotData:output_type -> swarm.RobotDataResponse
	4,  // 11: swarm.VisualiserService.SetSimulationPause:output_type -> swarm.SimulationPauseResponse
	11, // 12: swarm.VisualiserService.GetLeaderLog:output_type -> swarm.LeaderLogResponse
	13, // 13: swarm.VisualiserService.Kill:output_type -> swarm.KillResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_visualiser_proto_init() }
func file_visualiser_proto_init() {
	if File_visualiser_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_visualiser_proto_rawDesc), len(file_visualiser_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_visualiser_proto_goTypes,
		DependencyIndexes: file_visualiser_proto_depIdxs,
		EnumInfos:         file_visualiser_proto_enumTypes,
		MessageInfos:      file_visualiser_proto_msgTypes,
	}.Build()
	File_visualiser_proto = out.File
	file_visualiser_proto_goTypes = nil
	file_visualiser_proto_depIdxs = nil
}
