// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0--rc2
// source: proto/visualiser.proto

package communications

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VisualiserService_GetEnvironmentData_FullMethodName = "/swarm.VisualiserService/GetEnvironmentData"
	VisualiserService_GetRobotData_FullMethodName       = "/swarm.VisualiserService/GetRobotData"
	VisualiserService_SetSimulationPause_FullMethodName = "/swarm.VisualiserService/SetSimulationPause"
)

// VisualiserServiceClient is the client API for VisualiserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VisualiserServiceClient interface {
	// visualiser requests for environment data from the world.
	GetEnvironmentData(ctx context.Context, in *EnvironmentRequest, opts ...grpc.CallOption) (*EnvironmentResponse, error)
	// visualiser requests for robot data relevant to the visualiser from the world.
	GetRobotData(ctx context.Context, in *RobotDataRequest, opts ...grpc.CallOption) (*RobotDataResponse, error)
	// visualiser toggles simulation pause state across world and robots.
	SetSimulationPause(ctx context.Context, in *SimulationPauseRequest, opts ...grpc.CallOption) (*SimulationPauseResponse, error)
}

type visualiserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVisualiserServiceClient(cc grpc.ClientConnInterface) VisualiserServiceClient {
	return &visualiserServiceClient{cc}
}

func (c *visualiserServiceClient) GetEnvironmentData(ctx context.Context, in *EnvironmentRequest, opts ...grpc.CallOption) (*EnvironmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvironmentResponse)
	err := c.cc.Invoke(ctx, VisualiserService_GetEnvironmentData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualiserServiceClient) GetRobotData(ctx context.Context, in *RobotDataRequest, opts ...grpc.CallOption) (*RobotDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RobotDataResponse)
	err := c.cc.Invoke(ctx, VisualiserService_GetRobotData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *visualiserServiceClient) SetSimulationPause(ctx context.Context, in *SimulationPauseRequest, opts ...grpc.CallOption) (*SimulationPauseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulationPauseResponse)
	err := c.cc.Invoke(ctx, VisualiserService_SetSimulationPause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VisualiserServiceServer is the server API for VisualiserService service.
// All implementations must embed UnimplementedVisualiserServiceServer
// for forward compatibility.
type VisualiserServiceServer interface {
	// visualiser requests for environment data from the world.
	GetEnvironmentData(context.Context, *EnvironmentRequest) (*EnvironmentResponse, error)
	// visualiser requests for robot data relevant to the visualiser from the world.
	GetRobotData(context.Context, *RobotDataRequest) (*RobotDataResponse, error)
	// visualiser toggles simulation pause state across world and robots.
	SetSimulationPause(context.Context, *SimulationPauseRequest) (*SimulationPauseResponse, error)
	mustEmbedUnimplementedVisualiserServiceServer()
}

// UnimplementedVisualiserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVisualiserServiceServer struct{}

func (UnimplementedVisualiserServiceServer) GetEnvironmentData(context.Context, *EnvironmentRequest) (*EnvironmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEnvironmentData not implemented")
}
func (UnimplementedVisualiserServiceServer) GetRobotData(context.Context, *RobotDataRequest) (*RobotDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRobotData not implemented")
}
func (UnimplementedVisualiserServiceServer) SetSimulationPause(context.Context, *SimulationPauseRequest) (*SimulationPauseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSimulationPause not implemented")
}
func (UnimplementedVisualiserServiceServer) mustEmbedUnimplementedVisualiserServiceServer() {}
func (UnimplementedVisualiserServiceServer) testEmbeddedByValue()                           {}

// UnsafeVisualiserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VisualiserServiceServer will
// result in compilation errors.
type UnsafeVisualiserServiceServer interface {
	mustEmbedUnimplementedVisualiserServiceServer()
}

func RegisterVisualiserServiceServer(s grpc.ServiceRegistrar, srv VisualiserServiceServer) {
	// If the following call panics, it indicates UnimplementedVisualiserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VisualiserService_ServiceDesc, srv)
}

func _VisualiserService_GetEnvironmentData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvironmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).GetEnvironmentData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_GetEnvironmentData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).GetEnvironmentData(ctx, req.(*EnvironmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualiserService_GetRobotData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).GetRobotData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_GetRobotData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).GetRobotData(ctx, req.(*RobotDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VisualiserService_SetSimulationPause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulationPauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VisualiserServiceServer).SetSimulationPause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VisualiserService_SetSimulationPause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VisualiserServiceServer).SetSimulationPause(ctx, req.(*SimulationPauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VisualiserService_ServiceDesc is the grpc.ServiceDesc for VisualiserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VisualiserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swarm.VisualiserService",
	HandlerType: (*VisualiserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEnvironmentData",
			Handler:    _VisualiserService_GetEnvironmentData_Handler,
		},
		{
			MethodName: "GetRobotData",
			Handler:    _VisualiserService_GetRobotData_Handler,
		},
		{
			MethodName: "SetSimulationPause",
			Handler:    _VisualiserService_SetSimulationPause_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/visualiser.proto",
}
